candidate/urls.py
from django.urls import path
from .views import candidateProfileView,\
    candidateIndexView,\
    candidateSignupView,\
    candidateLoginView,\
    candidateLogoutView, \
    candidateUpdateView, \
    candidateAssessmentView

app_name = 'candidate'
urlpatterns = [
    path('',candidateIndexView,name='candidate-index'),
    path('assessment/',candidateAssessmentView,name='candidate-assessment'),
    path('profile/',candidateProfileView,name='candidate-profile'),
    path('signup/',candidateSignupView,name='candidate-signup'),
    path('login/',candidateLoginView,name='candidate-login'),
    path('logout/',candidateLogoutView,name='candidate-logout'),
    path('edit/<int:pk>',candidateUpdateView,name='candidate-edit'),
]

interview_portal/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings
from django.views.generic import TemplateView

urlpatterns = [
    path('',TemplateView.as_view(template_name='home.html'),name='index'),
    path('candidate/',include('candidate.urls',namespace='candidate')),
    path('employee/',include('employee.urls',namespace='employee')),
    path('admin/',include('empadmin.urls',namespace='admin')),
    path('jobs/',include('jobs.urls',namespace='jobs')),
    
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

jobs/urls.py
# urls.py
from django.urls import path
from . import views

app_name = 'jobs'

urlpatterns = [
    path('', views.job_list, name='job-list'),
    path('<int:pk>/', views.job_detail, name='job-detail'),
    path('create/', views.create_job, name='create-job'),
    path('<int:pk>/selectexam/<str:exam>', views.select_exam, name='select-exam'),
    path('<int:pk>/update/', views.update_job, name='update-job'),
    path('<int:pk>/delete/', views.delete_job, name='delete-job'),
]

candidate/forms.py
from django import forms
from .models import Candidate
from django.contrib.auth.models import User

class DateInput(forms.DateInput):
    input_type = 'date'

class CandidateCreateForm(forms.ModelForm):
    class Meta:
        model = Candidate
        fields = ['first_name', 'last_name', 'phone', 'dateofbirth','experience',
                    'noticeperiod','source','skill','resume']
        NOTICEPERIOD_CHOICES = (
                ('', 'Select Notice Period'),
                (1,1), #First one is the value of select option and second is the displayed value in option
                (2,2),
                (3,3),
                )
        widgets = {
            'dateofbirth': DateInput(),
            'noticeperiod': forms.Select(choices=NOTICEPERIOD_CHOICES,attrs={'class': 'form-control'}),
        }

class CandidateUpdateForm(forms.ModelForm):
    class Meta:
        model = Candidate
        fields = ['first_name', 'last_name', 'dateofbirth','experience',
                    'noticeperiod','source','skill','resume']
        NOTICEPERIOD_CHOICES = (
                ('', 'Select Notice Period'),
                (1,1), #First one is the value of select option and second is the displayed value in option
                (2,2),
                (3,3),
                )
        widgets = {
            'dateofbirth': DateInput(),
            'noticeperiod': forms.Select(choices=NOTICEPERIOD_CHOICES,attrs={'class': 'form-control'}),
        }

class CandidateSignupForm(forms.ModelForm):
    password = forms.CharField(label='Password', max_length=120, required=True,
                                       widget=forms.PasswordInput())
    password_confirm = forms.CharField(label='Confirm_Password', max_length=120,
                                       required=True, widget=forms.PasswordInput())
    class Meta:
        model = User
        fields = ['username','email','password','password_confirm']

    def clean(self):
        cleaned_data = super().clean()
        pass_0 = cleaned_data.get('password')
        pass_1 = cleaned_data.get('password_confirm')
        if pass_0 != pass_1:
            raise forms.ValidationError('Both password should be matched')


class CandidateLoginForm(forms.Form):
    username = forms.CharField(label = 'Username', max_length=120, required=True)
    password = forms.CharField(label = 'Password', max_length=120, required=True,widget=forms.PasswordInput())

    def clean(self):
        cleaned_data = super().clean()
        username = cleaned_data.get('username')
        if not User.objects.filter(username = username).exists():
            raise forms.ValidationError('Username not exists')

candidate/views.py
from django.shortcuts import render,get_object_or_404
from django.views.generic import CreateView,ListView,TemplateView
from django.contrib.auth.models import User,Group
from django.contrib.auth import authenticate,login,logout
from django.http import HttpResponseRedirect,Http404
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.core.mail import send_mail
from django.template.loader import render_to_string
from django.utils.html import strip_tags
from django.conf import settings
from django.urls import reverse
from .forms import CandidateCreateForm,CandidateSignupForm,CandidateLoginForm,CandidateUpdateForm
from .models import Candidate,CandidateResult,CandidateQuestionModel
import json,random

def send_mail_candidate(mail_template,context,email,subject='Interview Update'):
    subject = subject
    html_message = render_to_string(f'candidate/{mail_template}.html', context)
    plain_message = strip_tags(html_message)
    from_email = settings.EMAIL_HOST_USER
    to = email
    send_mail(subject, plain_message, from_email, [to], html_message=html_message)

def candidateIndexView(request):
    candidate = {}
    assessment = False
    if request.user.is_staff:
        logout(request)
        messages.warning(request, 'Access Denied.')
        return HttpResponseRedirect(reverse('index'))
    
    if request.user.is_anonymous:
        status = 'NOTLOGGED'
    else:
        qs = Candidate.objects.filter(username=request.user)
        qs_result = CandidateResult.objects.filter(candidate_id=qs.first())
        candidate = qs_result.first()
        if qs.exists():
            status = qs.first().status
            assessment = qs.first().assessment_result
    return render(request, 'candidate/index.html', {'status':status,'candidate':candidate,'assessment':assessment})

@login_required(login_url="/candidate/login/") 
def candidateProfileView(request):
    if request.user.is_staff:
        logout(request)
        messages.warning(request, 'Access Denied.')
        return HttpResponseRedirect(reverse('index'))
    
    file = None
    form = CandidateCreateForm(request.POST or None,request.FILES)
    qs = Candidate.objects.filter(username=request.user)
    if qs.exists():
        file = str(qs.first().resume).split('/')[-1]

    if form.is_valid():
        user = User.objects.get(username=request.user)
        first_name = form.cleaned_data['first_name']
        last_name = form.cleaned_data['last_name']
        email = user.email
        phone = form.cleaned_data['phone']
        dateofbirth = form.cleaned_data['dateofbirth']
        experience = form.cleaned_data['experience']
        noticeperiod = form.cleaned_data['noticeperiod']
        source = form.cleaned_data['source']
        skill = form.cleaned_data['skill']
        Candidate.objects.create(username=user,
                                 first_name=first_name,
                                 last_name=last_name,
                                 email=email,
                                 phone=phone,
                                 dateofbirth=dateofbirth,
                                 experience=experience,
                                 noticeperiod=noticeperiod,
                                 source=source,
                                 skill=skill,
                                 resume = request.FILES['resume'])
        user.first_name = first_name
        user.last_name = last_name
        user.save()
        messages.success(request, 'Candidate registration is completed.')
        send_mail_candidate('registration',{'first_name':first_name,'last_name':last_name},email)
        return HttpResponseRedirect(reverse('candidate:candidate-profile'))
    else:
        return render(request, 'candidate/profile.html', {'form': form,'done':qs.exists(),'qs':qs.first(),'file':file})

def candidateSignupView(request):
    form = CandidateSignupForm(request.POST or None)
    if form.is_valid():
        username = form.cleaned_data.get('username')
        password = form.cleaned_data.get('password')
        email = form.cleaned_data.get('email')
        User.objects.create_user(
            username = username,
            password=password,
            email=email
        )
        send_mail_candidate('signup_mail',{'username':username},email)
        messages.success(request,'Candidate signup is done.')
        return HttpResponseRedirect(reverse('candidate:candidate-login'))
    else:
        return render(request,'candidate/signup.html',{'form':form})

def candidateLoginView(request):  
    form = CandidateLoginForm(request.POST or None)
    if form.is_valid():
        username = form.cleaned_data.get('username')
        password = form.cleaned_data.get('password')
        django_user = User.objects.get(username=username)
        if not django_user.is_staff:
            user = authenticate(username=username, password=password)
            if user:
                login(request, user)
                send_mail_candidate('login_mail',{'first_name':django_user.first_name,'last_name':django_user.last_name},django_user.email)
                return HttpResponseRedirect(reverse('candidate:candidate-index'))
            else:
                messages.error(request, 'Invalid Credentials')
                return HttpResponseRedirect(reverse('candidate:candidate-login'))
        else:
            messages.error(request, 'Please register as Candidate and login again.')
            return HttpResponseRedirect(reverse('candidate:candidate-login'))
    return render(request,'candidate/login.html',{'form':form})

@login_required(login_url="/candidate/login/") 
def candidateLogoutView(request):
    logout(request)
    messages.success(request, 'Logout Done.')
    return HttpResponseRedirect(reverse('candidate:candidate-index'))

@login_required(login_url="/candidate/login/") 
def candidateUpdateView(request,pk=None):
    if request.user.is_staff:
        logout(request)
        messages.warning(request, 'Access Denied.')
        return HttpResponseRedirect(reverse('index'))
    qs_update = get_object_or_404(Candidate,id=pk)
    user = User.objects.get(username=request.user)
    form = CandidateUpdateForm(request.POST or None,request.FILES or None,instance=qs_update)
    if form.is_valid():
        instance = form.save(commit=False)
        instance.save(update_fields=['first_name', 'last_name', 'dateofbirth','experience',
                    'noticeperiod','source','skill','resume'])
        user.first_name = form.cleaned_data.get('first_name')
        user.last_name = form.cleaned_data.get('last_name')
        user.save()
        return HttpResponseRedirect(reverse('candidate:candidate-profile'))
    context = {'form': form}
    return render(request, template_name='candidate/edit.html', context=context)

@login_required(login_url="/candidate/login/") 
def candidateAssessmentView(request):
    if request.user.is_staff:
        logout(request)
        messages.warning(request, 'Access Denied.')
        return HttpResponseRedirect(reverse('index'))
    if request.method == 'POST':
        print(request.POST)
        score=0
        wrong=0
        correct=0
        total=25
        for key,value in request.POST.items():
            if key in ['csrfmiddlewaretoken','timer','question']:
                pass
            else:
                question_data = CandidateQuestionModel.objects.filter(id = int(key)).first()
                if question_data.answer == value:
                    score+=10
                    correct+=1
                else:
                    wrong+=1

        percent = score/(total*10) *100
        context = {
            'score':score,
            'correct':correct,
            'wrong':wrong,
            'percent':percent,
            'total':total,
            'status':'Cleared' if score >= 180 else 'Not Cleared'
        }
        candidate = Candidate.objects.get(username=request.user)
        candidate.assessment_data = json.dumps(context)
        candidate.assessment_result = True
        if score < 180:
            candidate.status = 'Rejected'
        candidate.save()
        if score >= 180:
            send_mail_candidate('test_clear_mail',{'first_name':candidate.first_name,'last_name':candidate.last_name},candidate.email)
        else:
            send_mail_candidate('rejected_mail',{'first_name':candidate.first_name,'last_name':candidate.last_name},candidate.email)

        return render(request,'candidate/result.html',context)
    else:
        candidate = Candidate.objects.get(username=request.user)
        if candidate.assessment_result == True:
            return render(request,'candidate/result.html',context=json.loads(candidate.assessment_data))
        questions=CandidateQuestionModel.objects.filter(skill=candidate.skill)
        questions = list(set(questions))

        # Shuffle the list to ensure randomness
        random.shuffle(questions)
        # Get 25 random unique elements from the list
        random_unique_elements = random.sample(questions, 25)

        skill = candidate.skill
        return render(request, template_name='candidate/questionnaire.html', context={'questions':random_unique_elements,'skill':skill})

candidate/templates/candidate/base.html
<!doctype html>
{% load static %}
<html lang="en" class="h-100">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Hugo 0.82.0">
    <title>Interview Portal</title>
    <!-- Bootstrap core CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/js/bootstrap.bundle.min.js" integrity="sha384-JEW9xMcG8R+pH31jmWH6WWP0WintQrMb4s7ZOdauHnUtxwoG2vI5DkLtS3qm9Ekf" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="{% static 'css/styles.css' %}" />
  </head>
  <body class="d-flex text-center text-white bg-dark">
    <div class="cover-container d-flex w-100 h-100 p-3 mx-auto flex-column min-vh-100">
    <header class="mb-auto">
      <div>
        <h3 class="float-md-start mb-0">Interview Portal</h3>
        <nav class="nav nav-masthead justify-content-center float-md-end">
          <a class="nav-link" aria-current="page" href="{% url 'candidate:candidate-index' %}">Home</a>
          {% if user.is_authenticated %}
          <a class="nav-link" href="{% url 'candidate:candidate-profile' %}">Profile</a>
          {% if status != 'No Status' or assessment %}
          <a class="nav-link" href="{% url 'candidate:candidate-assessment' %}">Assessment</a>
          {% endif %}
          <a class="nav-link" href="{% url 'candidate:candidate-logout' %}">Logout</a>
          {% else %}
          <a class="nav-link" href="{% url 'candidate:candidate-signup' %}">Signup</a>
          <a class="nav-link" href="{% url 'candidate:candidate-login' %}"> Login</a>
          {% endif %}
        </nav>
      </div>
    </header>
      {% block content %}
        {% endblock %}
      <footer class="mt-auto text-white-50">
        <div>
          &copy;
          <span id="copyright">
              <script>document.getElementById('copyright').appendChild(document.createTextNode(new Date().getFullYear()))</script>
          </span>
          Interview Portal
      </div>
        <p><a>Designed by Vishesh Agarwal</a></p>
      </footer>
    </div>
    <script>
      $(function () {
        $("#datetimepicker1").datetimepicker({
          format: 'DD/MM/YYYY HH:mm',
        });
      });
    </script>
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script>window.jQuery || document.write('<script src="/docs/4.5/assets/js/vendor/jquery.slim.min.js"><\/script>')</script>
    {% block script %}
        {% endblock %}
  </body>
</html>

candidate/templates/candidate/edit.html
{% extends 'candidate/base.html' %}
{% load crispy_forms_tags %}
{% block content %}
<div class ='cover-container d-flex w-100 h-100 p-5 mx-auto flex-column'>
    <br>
    {% for message in messages %}
        <div class="alert alert-success">
        {{ message }}
        </div>
    {% endfor %}
    {% if not done %}
    <h2 class="text-center alert alert-info">Candidate Registration Form</h2>
    <form method="post" enctype="multipart/form-data">
      {% csrf_token %}
      <div class="form-row">
        <div class="form-group col-md-4 mb-0">
          {{ form.first_name|as_crispy_field }}
        </div>
        <div class="form-group col-md-4 mb-0">
          {{ form.last_name|as_crispy_field }}
        </div>
        <div class="form-group col-md-4 mb-0">
          {{ form.skill|as_crispy_field }}
        </div>
      </div>
      <div class="form-row">
        <div class="form-group col-md-4 mb-0">
          {{ form.dateofbirth|as_crispy_field }}
        </div>
        <div class="form-group col-md-4 mb-0">
            {{ form.experience|as_crispy_field }}
          </div>
          <div class="form-group col-md-4 mb-0">
            {{ form.noticeperiod|as_crispy_field }}
          </div>
      </div>
      <div class="form-row">
        <div class="form-group col-md-4 mb-0">
          {{ form.source|as_crispy_field }}
        </div>
        <div class="form-group col-md-4 mb-0">
            {{ form.resume|as_crispy_field }}
          </div>
      </div>
        <br><button class="w-100 btn btn-lg btn-primary" type="submit">Update</button>
    </form>
    {% endif %}
</div>
{% endblock %}

candidate/templates/candidate/index.html
{% extends 'candidate/base.html' %}
{% load crispy_forms_tags %}
{% load static %}
{% block content %}
    {% for message in messages %}
        <div class="alert alert-success">
        {{ message }}
        </div>
    {% endfor %}
    <h1>Interview Portal for Candidates</h1>
    <p class="lead">This innovative online platform designed to streamline and optimize the interview process for both recruiters and candidates. It serves as a centralized hub where recruiters can manage and conduct interviews efficiently, while candidates can easily signup, attend, and follow up on their interviews.</p>
    <br>
    {% if status != 'NOTLOGGED' %}
    <table class="table table-hover table-dark table-bordered align-middle mb-0">
      <colgroup>
        <col span="1" style="width: 5%;">
        <col span="1" style="width: 20%;">
        <col span="1" style="width: 10%;">
        <col span="1" style="width: 60%;">
     </colgroup>
      <thead class="bg-light">
        <tr>
          <th>Level</th>
          <th>Interviewer</th>
          <th>Status</th>
          <th>Feedback</th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <td>
            <div class="d-flex align-items-center">
              <div class="ms-3">
                <p class="fw-bold mb-1">L1</p>
              </div>
            </div>
          </td>
          {% if candidate.l1_by.employee_name %}
            <td><p class="fw-normal mb-1">{{ candidate.l1_by.employee_name}}</p><p class="text-muted mb-0">{{ candidate.l1_by.employee_skill}} Developer</p></td>
          {% else %}
          <td><p class="fw-normal mb-1">Not Assigned</p></td>
          {% endif %}
          <td><p class="fw-normal mb-1">{{ candidate.status_l1}}</p></td>
          {% if candidate.feedback_l2 != None %}
            <td><p class="fw-normal mb-1">{{ candidate.feedback_l1}}</p></td>
          {% else %}
          <td><p class="fw-normal mb-1"></p></td>
          {% endif %}
        </tr>
        <tr>
          <td>
            <div class="d-flex align-items-center">
              <div class="ms-3">
                <p class="fw-bold mb-1">L2</p>
              </div>
            </div>
          </td>
          {% if candidate.l2_by.employee_name %}
            <td><p class="fw-normal mb-1">{{ candidate.l2_by.employee_name}}</p><p class="text-muted mb-0">{{ candidate.l2_by.employee_skill}} Developer</p></td>
          {% else %}
          <td><p class="fw-normal mb-1">Not Assigned</p></td>
          {% endif %}
          <td><p class="fw-normal mb-1">{{ candidate.status_l2}}</p></td>
          {% if candidate.feedback_l2 != None %}
            <td><p class="fw-normal mb-1">{{ candidate.feedback_l2}}</p></td>
          {% else %}
          <td><p class="fw-normal mb-1"></p></td>
          {% endif %}
        </tr>
        <tr>
          <td>
            <div class="d-flex align-items-center">
              <div class="ms-3">
                <p class="fw-bold mb-1">HR</p>
              </div>
            </div>
          </td>
          {% if candidate.hr_by.employee_name  %}
            <td><p class="fw-normal mb-1">{{ candidate.hr_by.employee_name}}</p><p class="text-muted mb-0">{{ candidate.l1_by.employee_skill}} Developer</p></td>
          {% else %}
          <td><p class="fw-normal mb-1">Not Assigned</p></td>
          {% endif %}
          <td><p class="fw-normal mb-1">{{ candidate.status_hr}}</p></td>
          {% if candidate.feedback_hr != None %}
            <td><p class="fw-normal mb-1">{{ candidate.feedback_hr}}</p></td>
          {% else %}
          <td><p class="fw-normal mb-1"></p></td>
          {% endif %}
        </tr>
      </tbody>
    </table>
    <br>
    {% endif %}
{% endblock %}

candidate/templates/candidate/login.html
{% extends 'candidate/base.html' %}
{% load crispy_forms_tags %}
{% block content %}
<div class ='cover-container d-flex w-50 h-100 p-5 mx-auto flex-column'>
    <br>
    <h2 class="text-center alert alert-info">Candidate Login</h2>
    {% for message in messages %}
        <div class="alert alert-success">
        {{ message }}
        </div>
    {% endfor %}
    <form method="post">
      {% csrf_token %}
      {{ form | crispy }}
        <br><button class="w-100 btn btn-lg btn-primary" type="submit">Login</button>
    </form>
</div>

{% endblock %}

candidate/templates/candidate/mail_template.html
<!DOCTYPE html>
<html lang="en">

  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    {% block title %}

    {% endblock %}
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/css/bootstrap.min.css" rel="stylesheet"
      integrity="sha384-wEmeIV1mKuiNpC+IOBjI7aAzPcEZeedi5yW5f2yOq55WWLwNGmvvx4Um1vskeMj0" crossorigin="anonymous" />
  </head>

  <body>
    {% block body %}

    {% endblock %}
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-p34f1UUtsS3wqzfto5wAAmdvj+osOnFyQFpp4Ua3gs/ZVWx6oOypYoCJhGGScy+8" crossorigin="anonymous">
    </script>
  </body>

</html>

candidate/templates/candidate/profile.html
{% extends 'candidate/base.html' %}
{% load crispy_forms_tags %}
{% block content %}
<div class ='cover-container d-flex w-100 h-100 p-5 mx-auto flex-column'>
    {% for message in messages %}
        <div class="alert alert-success">
        {{ message }}
        </div>
    {% endfor %}
    {% if not done %}
    <h2 class="text-center alert alert-info">Candidate Registration Form</h2>
    <form method="post" enctype="multipart/form-data">
      {% csrf_token %}
      <div class="form-row">
        <div class="form-group col-md-4 mb-0">
          {{ form.first_name|as_crispy_field }}
        </div>
        <div class="form-group col-md-4 mb-0">
          {{ form.last_name|as_crispy_field }}
        </div>
        <div class="form-group col-md-4 mb-0">
          {{ form.skill|as_crispy_field }}
        </div>
      </div>
      <div class="form-row">
        <div class="form-group col-md-4 mb-0">
          {{ form.phone|as_crispy_field }}
        </div>
        <div class="form-group col-md-4 mb-0">
          {{ form.dateofbirth|as_crispy_field }}
        </div>
        <div class="form-group col-md-4 mb-0">
          {{ form.experience|as_crispy_field }}
        </div>
      </div>
      <div class="form-row">
        <div class="form-group col-md-4 mb-0">
          {{ form.noticeperiod|as_crispy_field }}
        </div>
        <div class="form-group col-md-4 mb-0">
          {{ form.source|as_crispy_field }}
        </div>
        <div class="form-group col-md-4 mb-0">
          {{ form.resume|as_crispy_field }}
        </div>
      </div>
        <button class="w-100 btn btn-lg btn-primary" type="submit">Create</button>
    </form>
    {% else %}
        <h2 class="text-center alert alert-warning">Candidate Information</h2>
        <table class="table table-dark table-bordered">
          <tbody>
            <tr>
              <td>Username</td>
              <td>{{ qs.username }}</td>
            </tr>
            <tr>
              <td>First Name</td>
              <td>{{ qs.first_name }}</td>
            </tr>
          <tr>
              <td>last Name</td>
              <td>{{ qs.last_name }}</td>
            </tr>
          <tr>
              <td>Email</td>
              <td>{{ qs.email }}</td>
            </tr>
          <tr>
              <td>Phone</td>
              <td>{{ qs.phone }}</td>
            </tr>
          <tr>
              <td>Date of Birth</td>
              <td>{{ qs.dateofbirth }}</td>
            </tr>
          <tr>
              <td>Experience</td>
              <td>{{ qs.experience }}</td>
            </tr>
          <tr>
              <td>Notice Period</td>
              <td>{{ qs.noticeperiod }}</td>
            </tr>
          <tr>
              <td>Source</td>
              <td>{{ qs.source }}</td>
            </tr>
          <tr>
              <td>Skill</td>
              <td>{{ qs.skill }}</td>
            </tr><tr>
              <td>Status</td>
              <td>{{ qs.status }}</td>
            </tr>
          <tr>
              <td>Resume</td>
              <td><a href="{{qs.resume.url}}">{{ file }}</a></td>
            </tr>
          </tbody>
        </table>
        <div class="d-grid gap-2 col-6 mx-auto">
          <a href="{% url 'candidate:candidate-edit' qs.id %}" class="btn btn-light btn-sm">Edit</a>
        </div>
        
    {% endif %}
</div>
{% endblock %}

candidate/templates/candidate/registration.html
{% extends 'candidate/mail_template.html' %}

{% block body %}
<div style="max-width: 600px; margin: 0 auto; padding: 20px; background-color: #f8f8f8; border-radius: 10px;">
    <h2 style="color: #333333;">Welcome to Interview Portal!</h2>
    <p style="color: #666666;">Dear {{first_name}} {{last_name}},</p>
    <p style="color: #666666;">Congratulations! You've successfully updated your profile on Interview Portal. Please complete your assessment first.</p>
    <p style="color: #666666;">Post which interview process will start soon. Interview Process have three levels L1,L2,HR.</p>
    <p style="color: #666666;">With your new account, you can now access all the features and benefits our platform offers.</p>
    <p style="color: #666666;">If you have any questions, need assistance, or want to provide feedback, feel free to reach out to our support team. We're here to help!</p>
    <p style="color: #666666;">Thank you for choosing Interview Portal. We look forward to seeing you around!</p>
    <p style="color: #666666;">Best regards,</p>
    <p style="color: #666666;">Vishesh Agarwal<br>Python Developer</p>
</div>
{% endblock %}

candidate/templates/candidate/rejected_mail.html
{% extends 'candidate/mail_template.html' %}

{% block title %}
    <title>Notification: Application Status Update</title>
{% endblock %}
{% block body %}
<div style="max-width: 600px; margin: 0 auto; padding: 20px; background-color: #f8f8f8; border-radius: 10px;">
    <h2 style="color: #333333;">Application Status Update</h2>
    <p style="color: #666666;">Dear {{first_name}} {{last_name}},</p>
    <p style="color: #666666;">We regret to inform you that after careful consideration, we have decided not to move forward with your application.</p>
    <p style="color: #666666;">We sincerely appreciate the time and effort you invested in the application process and want to thank you for your interest in joining our team.</p>
    <p style="color: #666666;">While your qualifications and experience are impressive, we received a large number of highly qualified applicants, and unfortunately, we could only select a few candidates for further consideration.</p>
    <p style="color: #666666;">Please do not be discouraged by this decision, as it does not reflect on your abilities or potential. We encourage you to continue pursuing opportunities that align with your skills and career goals.</p>
    <p style="color: #666666;">Thank you again for your interest, and we wish you all the best in your future endeavors.</p>
    <p style="color: #666666;">Best regards,</p>
    <p style="color: #666666;">Vishesh Agarwal<br>Python Developer<br></p>
</div>
{% endblock %}

candidate/templates/candidate/signup.html
{% extends 'candidate/base.html' %}
{% load crispy_forms_tags %}
{% block content %}
<div class ='cover-container d-flex w-50 h-100 p-5 mx-auto flex-column'>
    {% for message in messages %}
        <div class="alert alert-success">
        {{ message }}
        </div>
    {% endfor %}
    <br>
    <h2 class="text-center alert alert-info">Candidate Signup</h2>
    <form method="post">
      {% csrf_token %}
      {{ form | crispy }}
        <br><button class="w-100 btn btn-lg btn-primary" type="submit">Signup</button>
    </form>
</div>
{% endblock %}