employee/urls.py
from django.urls import path
from . import views

app_name = 'employee'
urlpatterns = [
    path('',views.employeeIndexView,name='employee-index'),
    path('profile/',views.employeeProfileView,name='employee-profile'),
    path('status/<str:status>',views.employeeStatusList,name='employee-status'),
    path('list/?page=n',views.employeeListView,name='employee-list'),
    path('signup/',views.employeeSignupView,name='employee-signup'),
    path('feedback/<int:id>/',views.employeeFeedback,name='employee-feedback'),
    path('login/',views.employeeLoginView,name='employee-login'),
    path('logout/',views.employeeLogoutView,name='employee-logout'),
]

interview_portal/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings
from django.views.generic import TemplateView

urlpatterns = [
    path('',TemplateView.as_view(template_name='home.html'),name='index'),
    path('candidate/',include('candidate.urls',namespace='candidate')),
    path('employee/',include('employee.urls',namespace='employee')),
    path('admin/',include('empadmin.urls',namespace='admin')),
    path('jobs/',include('jobs.urls',namespace='jobs')),
    
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

jobs/urls.py
# urls.py
from django.urls import path
from . import views

app_name = 'jobs'

urlpatterns = [
    path('', views.job_list, name='job-list'),
    path('<int:pk>/', views.job_detail, name='job-detail'),
    path('create/', views.create_job, name='create-job'),
    path('<int:pk>/selectexam/<str:exam>', views.select_exam, name='select-exam'),
    path('<int:pk>/update/', views.update_job, name='update-job'),
    path('<int:pk>/delete/', views.delete_job, name='delete-job'),
]

candidate/models.py
from django.db import models
from django.utils.encoding import smart_text
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.contrib.auth.models import User
from employee.models import Employee
from django.core.files.storage import FileSystemStorage

# Create your models here.
class Candidate(models.Model):
    source_choices = (('Referral', 'Referral'), ('Job Portal', 'Job Portal'), ('Walk In', 'Walk In'))
    skill_choices = (('Python', 'Python'), ('Java', 'Java'))
    result_choice = (('Selected', 'Selected'), ('Rejected', 'Rejected'), ('Pending', 'Pending'))

    username = models.OneToOneField(User,related_name='+',on_delete=models.CASCADE)
    first_name = models.CharField(verbose_name='First Name',null=False,blank=False,max_length=50)
    last_name = models.CharField(verbose_name='Last Name',null=False,blank=False,max_length=50)
    email = models.EmailField(verbose_name='Email',unique=True,null=False,blank=False)
    phone = models.PositiveBigIntegerField(verbose_name='Phone Number',unique=True,null=False,blank=False)
    dateofbirth = models.DateField(verbose_name='Date of Birth',null=False,blank=False)
    experience = models.DecimalField(verbose_name='Experience',null=False,blank=False,max_digits=5, decimal_places=2,help_text='Please enter in years')
    noticeperiod = models.IntegerField(verbose_name='Notice Period', blank=False, null=False,help_text='Please enter in months')
    source = models.CharField(verbose_name='Source', max_length=10, choices=source_choices, default='Walk In')
    skill = models.CharField(max_length=10, default='Python', choices=skill_choices, null=False, blank=False)
    resume = models.FileField(verbose_name='Resume', upload_to='documents/')
    created_at = models.DateTimeField(verbose_name='Created At', auto_now=False, auto_now_add=True)
    updated_at = models.DateTimeField(verbose_name='Updated At', auto_now=True, auto_now_add=False)
    status = models.CharField(verbose_name='Status', default='Pending',choices=result_choice , max_length= 50)
    assessment_data = models.JSONField(verbose_name='Score', null=True)
    assessment_result = models.BooleanField(default=False)

    class Meta:
        ordering = ['-created_at','-updated_at']
        verbose_name = "Candidate"
        verbose_name_plural = "Candidates"

    def __str__(self):
        return smart_text(self.username)

    def __unicode__(self):
        return smart_text(self.username)

class CandidateResult(models.Model):
    result_choice   = (('Selected','Selected'),('Rejected','Rejected'),('Pending','Pending'))
    candidate_id    = models.ForeignKey(Candidate,related_name='+',on_delete=models.CASCADE)
    status_l1       = models.CharField(verbose_name='L1 Status', default='Pending',choices=result_choice , max_length= 50)
    feedback_l1     = models.TextField(verbose_name='L1 Feedback', null=True, blank=True)
    l1_by           = models.ForeignKey(Employee,related_name='+',on_delete=models.CASCADE, null=True, blank=True)
    l1_at           = models.DateTimeField(verbose_name='L1 Date',null=True)
    status_l2       = models.CharField(verbose_name='L2 Status', default='Pending',choices=result_choice , max_length= 50)
    feedback_l2     = models.TextField(verbose_name='L2 Feedback', null=True, blank=True)
    l2_by           = models.ForeignKey(Employee, related_name='+', on_delete=models.CASCADE, null=True, blank=True)
    l2_at           = models.DateTimeField(verbose_name='L2 Date',null=True)
    status_hr       = models.CharField(verbose_name='HR Status', default='Pending',choices=result_choice , max_length= 50)
    feedback_hr     = models.TextField(verbose_name='HR Feedback', null=True, blank=True)
    hr_by           = models.ForeignKey(Employee, related_name='+', on_delete=models.CASCADE, null=True, blank=True)
    hr_at           = models.DateTimeField(verbose_name='HR Date',null=True)

# method for updating
@receiver(post_save, sender=Candidate)
def update_stock(sender, instance, **kwargs):
    CandidateResult.objects.get_or_create(candidate_id=instance)

# Create your models here.
class CandidateQuestionModel(models.Model):
    skill_choices = (('Python', 'Python'), ('Java', 'Java'))
    question = models.CharField(max_length=200,null=True)
    skill = models.CharField(max_length=10, default='Python', choices=skill_choices, null=False, blank=False)
    option1 = models.CharField(max_length=200,null=True)
    option2 = models.CharField(max_length=200,null=True)
    option3 = models.CharField(max_length=200,null=True)
    option4 = models.CharField(max_length=200,null=True)
    answer  = models.CharField(max_length=200,null=True)
    
    def __str__(self):
        return self.question

employee/models.py
from django.db import models
from django.contrib.auth.models import User

class Employee(models.Model):
    skill_choices  = (('Python','Python'),('Java','Java'))
    level_choices  = (('L1','L1'),('L2','L2'),('HR','HR'))
    approval_choices  = (('Approved','Approved'),('Rejected','Rejected'),('Pending','Pending'))

    employee_username   = models.OneToOneField(User,related_name='+',on_delete=models.CASCADE)
    employee_name       = models.CharField(verbose_name = 'Employee Name', max_length=50)
    employee_email      = models.EmailField(verbose_name = 'Official Email',unique = True,null = False,blank = False)
    employee_skill      = models.CharField(verbose_name = 'Skill',max_length=50,choices = skill_choices,null = False,blank = False)
    employee_level      = models.CharField(verbose_name= 'Level',max_length=50,choices = level_choices,null = False,blank = False)
    employee_status     = models.CharField(verbose_name='Approval Status', default='Pending',choices=approval_choices , max_length= 50)

    class Meta:
        verbose_name = "Employee"
        verbose_name_plural = "Employees"

    def __str__(self):
        return self.employee_name

employee/views.py
from django.shortcuts import render
from django.contrib.auth.models import User,Group
from django.contrib.auth import authenticate,login,logout
from django.db.models import Q
from django.http import HttpResponseRedirect
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.urls import reverse
import datetime
from .forms import EmployeeLoginForm,EmployeeSignupForm,EmployeeProfileForm,EmployeeFeedbackForm
from .models import Employee
from candidate.models import Candidate,CandidateResult
from candidate.views import send_mail_candidate

def isEmployee(employee):
    emp_qs = Employee.objects.filter(employee_username=employee)
    return emp_qs.exists()

def employeeIndexView(request):
    if not request.user.is_staff and request.user.is_authenticated:
        logout(request)
        messages.warning(request, 'Access Denied.')
        return HttpResponseRedirect(reverse('index'))

    registered = False
    if request.user.is_staff and Employee.objects.filter(employee_username=request.user,employee_status='Approved').exists():
        registered = True
    return render(request, 'employee/index.html', {'registered': registered})

@login_required(login_url="/employee/login/")
def employeeListView(request):
    if not request.user.is_staff or not isEmployee(request.user):
        logout(request)
        messages.warning(request, 'Access Denied.')
        return HttpResponseRedirect(reverse('index'))

    registered = False
    qs_employee = Employee.objects.filter(employee_username=request.user).first()

    if qs_employee.employee_status == 'Pending':
        messages.warning(request, 'Pending Approval.')
        return HttpResponseRedirect(reverse('employee:employee-index'))
    elif qs_employee.employee_status == 'Rejected':
        messages.warning(request, 'Approval Rejected.')
        return HttpResponseRedirect(reverse('employee:employee-index'))
    
    if qs_employee.employee_status == 'Approved':
        registered = True

    skill = qs_employee.employee_skill
    level = qs_employee.employee_level
    if level == 'L1':
        candidate_list = CandidateResult.objects.filter(status_l1='Pending',candidate_id__skill=skill,candidate_id__assessment_result=True,candidate_id__status='Pending')
    elif level == 'L2':
        candidate_list = CandidateResult.objects.filter(status_l1='Selected',status_l2='Pending',candidate_id__skill=skill)
    elif level == 'HR':
        candidate_list = CandidateResult.objects.filter(status_l1='Selected',status_l2='Selected',status_hr='Pending')
    return render(request, 'employee/list.html', {'candidate_list': candidate_list,'registered':registered})

@login_required(login_url="/employee/login/") 
def employeeProfileView(request):
    if not request.user.is_staff:
        logout(request)
        messages.warning(request, 'Access Denied.')
        return HttpResponseRedirect(reverse('index'))
    
    registered = False
    candidate_selected,candidate_rejected = 0,0
    form = EmployeeProfileForm(request.POST or None)
    qs = Employee.objects.filter(employee_username=request.user)

    registered = False
    if qs.exists():
        level = qs.first().employee_level
        status = qs.first().employee_status
        filters_selected = {f'status_{level.lower()}':'Selected',f'{level.lower()}_by': qs.first()}
        filters_rejected = {f'status_{level.lower()}':'Rejected',f'{level.lower()}_by': qs.first()}
        candidate_selected = CandidateResult.objects.filter(**filters_selected).count()
        candidate_rejected = CandidateResult.objects.filter(**filters_rejected).count()
        if status == 'Approved':
            registered = True

    if form.is_valid():
        employee_username = User.objects.get(username=request.user)
        employee_name = form.cleaned_data['employee_name']
        employee_skill = form.cleaned_data['employee_skill']
        employee_level = form.cleaned_data['employee_level']
        Employee.objects.create(employee_username=employee_username,
                                 employee_name=employee_name,
                                 employee_skill=employee_skill,
                                 employee_email=request.user.email,
                                 employee_level=employee_level)
        messages.success(request, 'Profile is completed.')
        return HttpResponseRedirect(reverse('employee:employee-list'))
    else:
        return render(request, 'employee/profile.html', {'form': form,'done':qs.exists(),'qs':qs.first(),'registered':registered,'candidate_selected':candidate_selected,'candidate_rejected':candidate_rejected})

def employeeSignupView(request):     
    form = EmployeeSignupForm(request.POST or None)
    if form.is_valid():
        username = form.cleaned_data.get('username')
        password = form.cleaned_data.get('password')
        email = form.cleaned_data.get('email')
        User.objects.create_user(
            username = username,
            password=password,
            is_staff = True,
            email=email
        )
        messages.success(request,'Signup is Done.')
        return HttpResponseRedirect(reverse('employee:employee-login'))
    else:
        return render(request,'employee/signup.html',{'form':form})

def employeeLoginView(request):  
    form = EmployeeLoginForm(request.POST or None)
    if form.is_valid():
        username = form.cleaned_data.get('username')
        password = form.cleaned_data.get('password')
        django_user = User.objects.get(username=username)
        if django_user.is_staff:
            user = authenticate(username = username,password = password)
            if user:
                login(request,user)
                return HttpResponseRedirect(reverse('employee:employee-index'))
            else:
                messages.error(request,'Invalid Credentials')
                return HttpResponseRedirect(reverse('employee:employee-login'))
        else:
            messages.error(request, 'Please Register as Employee.')
            return HttpResponseRedirect(reverse('employee:employee-login'))
    return render(request,'employee/login.html',{'form':form})

@login_required(login_url="/employee/login/") 
def employeeStatusList(request,status):
    if not request.user.is_staff or not isEmployee(request.user):
        logout(request)
        messages.warning(request, 'Access Denied.')
        return HttpResponseRedirect(reverse('index'))
    
    qs_employee = Employee.objects.filter(employee_username=request.user).first()

    if qs_employee.employee_status == 'Pending':
        messages.warning(request, 'Pending Approval.')
        return HttpResponseRedirect(reverse('employee:employee-index'))
    elif qs_employee.employee_status == 'Rejected':
        messages.warning(request, 'Approval Rejected.')
        return HttpResponseRedirect(reverse('employee:employee-index'))

    registered = False
    if isEmployee(request.user) and qs_employee.employee_status == 'Approved':
        registered = True
    
    level = qs_employee.employee_level
    filters_status = {f'status_{level.lower()}':status,f'{level.lower()}_by': qs_employee}
    candidate_list = CandidateResult.objects.filter(**filters_status)
    return render(request, 'employee/selected_list.html', {'candidate_list': candidate_list, 'registered': registered,'level':level.lower()})

@login_required(login_url="/employee/login/") 
def employeeFeedback(request,id=None):
    if not request.user.is_staff or not isEmployee(request.user):
        logout(request)
        messages.warning(request, 'Access Denied.')
        return HttpResponseRedirect(reverse('index'))
    
    form = EmployeeFeedbackForm(request.POST or None)
    candidate = Candidate.objects.filter(id=id).first()
    qs_candidate_result = CandidateResult.objects.filter(candidate_id=candidate)
    qs_employee = Employee.objects.filter(employee_username=request.user).first()

    if qs_employee.employee_status == 'Pending':
        messages.warning(request, 'Pending Approval.')
        return HttpResponseRedirect(reverse('employee:employee-index'))
    elif qs_employee.employee_status == 'Rejected':
        messages.warning(request, 'Approval Rejected.')
        return HttpResponseRedirect(reverse('employee:employee-index'))
    
    registered = False
    if isEmployee(request.user) and qs_employee.employee_status == 'Approval':
        registered = True
    level = qs_employee.employee_level
    if form.is_valid():
        status = form.cleaned_data.get('status')
        feedback = form.cleaned_data.get('feedback')
        data = {f'feedback_{level.lower()}':feedback,
                f'status_{level.lower()}':status,
                f'{level.lower()}_by': qs_employee,
                f'{level.lower()}_at': datetime.datetime.now()}
        qs_candidate_result.update(**data)
        if level == 'HR' and status == 'Selected':
            Candidate.objects.filter(id=id).update(status='Selected')
        elif status == 'Rejected':
            Candidate.objects.filter(id=id).update(status='Rejected')
        send_mail_candidate(f'{status.lower()}_mail',{'first_name':candidate.first_name,'last_name':candidate.last_name,'level':level.upper()},candidate.email)
        return HttpResponseRedirect(reverse('employee:employee-list'))
    return render(request, 'employee/feedback.html',{'form': form, 'registered': registered,'candidate':candidate,'candidate_result':qs_candidate_result.first()})

@login_required(login_url="/employee/login/") 
def employeeLogoutView(request):
    logout(request)
    messages.success(request, 'Logout Done.')
    return HttpResponseRedirect(reverse('employee:employee-login'))

employee/templates/employee/base.html
<!doctype html>
{% load static %}
<html lang="en" class="h-100">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <title>Interview Portal</title>
    <!-- Bootstrap core CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/js/bootstrap.bundle.min.js" integrity="sha384-JEW9xMcG8R+pH31jmWH6WWP0WintQrMb4s7ZOdauHnUtxwoG2vI5DkLtS3qm9Ekf" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://cdn.datatables.net/1.13.4/css/dataTables.bootstrap5.min.css">
    <link rel="stylesheet" href="{% static 'css/styles.css' %}" />

  </head>
<body class="d-flex text-center text-white bg-dark">
  <div class="cover-container d-flex w-100 h-100 p-3 mx-auto flex-column min-vh-100">
  <header class="mb-auto">
    <div>
      <h3 class="float-md-start mb-0">Interview Portal</h3>
      <nav class="nav nav-masthead justify-content-center float-md-end">
        <a class="nav-link" aria-current="page" href="{% url 'employee:employee-index' %}">Home</a>
        {% if registered %}
        <a class="nav-link dropdown-toggle" href="#" id="navbarDarkDropdownMenuLink" role="button" data-bs-toggle="dropdown" aria-expanded="false">
          Candidates
        </a>
        <ul class="dropdown-menu dropdown-menu-dark" aria-labelledby="navbarDarkDropdownMenuLink">
          <li><a class="dropdown-item" href="{% url 'employee:employee-list' %}">List</a></li>
          <li><a class="dropdown-item" href="{% url 'employee:employee-status' 'Selected' %}">Selected</a></li>
          <li><a class="dropdown-item" href="{% url 'employee:employee-status' 'Rejected' %}">Rejected</a></li>
        </ul>
        &nbsp;&nbsp;&nbsp;
        {% endif %}
        {% if user.is_staff %}
        <a class="nav-link dropdown-toggle" href="#" id="navbarDarkDropdownMenuLink" role="button" data-bs-toggle="dropdown" aria-expanded="false">
          {{ request.user.username}}
        </a>
        <ul class="dropdown-menu dropdown-menu-dark" aria-labelledby="navbarDarkDropdownMenuLink">
          <li><a class="dropdown-item" href="{% url 'employee:employee-profile' %}">Profile</a></li>
          <li><a class="dropdown-item" href="{% url 'employee:employee-logout' %}">Logout</a></li>
        </ul>
        &nbsp;&nbsp;&nbsp;
        
        {% else %}
        <a class="nav-link" href="{% url 'employee:employee-signup' %}">Signup</a>
        <a class="nav-link" href="{% url 'employee:employee-login' %}"> Login</a>
        {% endif %}
      </nav>
    </div>
  </header>
  <br>
   {% block content %}
    {% endblock %}
    <br>
  <footer class="mt-auto text-white-50">
    <div>
      &copy;
      <span id="copyright">
          <script>document.getElementById('copyright').appendChild(document.createTextNode(new Date().getFullYear()))</script>
      </span>
      Interview Portal
  </div>
  <p><a>Designed by Vishesh Agarwal</a></p>
  </footer>
</div>
</body>
  <script src="https://code.jquery.com/jquery-3.7.0.min.js"></script>
  <script src="https://cdn.datatables.net/1.13.4/js/jquery.dataTables.min.js"></script>
  <script src="https://cdn.datatables.net/1.13.4/js/dataTables.bootstrap5.min.js"></script>
  <script>
    $(document).ready(function () {
    // Setup - add a text input to each footer cell
    $('#userTable thead tr')
        .clone(true)
        .addClass('filters')
        .appendTo('#userTable thead');
 
    var table = $('#userTable').DataTable({
        orderCellsTop: true,
        fixedHeader: true,
        initComplete: function () {
            var api = this.api();
 
            // For each column
            api
                .columns()
                .eq(0)
                .each(function (colIdx) {
                    // Set the header cell to contain the input element
                    var cell = $('.filters th').eq(
                        $(api.column(colIdx).header()).index()
                    );
                    var title = $(cell).text();
                    $(cell).html('<input type="text" placeholder="' + title + '" />');
 
                    // On every keypress in this input
                    $(
                        'input',
                        $('.filters th').eq($(api.column(colIdx).header()).index())
                    )
                        .off('keyup change')
                        .on('change', function (e) {
                            // Get the search value
                            $(this).attr('title', $(this).val());
                            var regexr = '({search})'; //$(this).parents('th').find('select').val();
 
                            var cursorPosition = this.selectionStart;
                            // Search the column for that value
                            api
                                .column(colIdx)
                                .search(
                                    this.value != ''
                                        ? regexr.replace('{search}', '(((' + this.value + ')))')
                                        : '',
                                    this.value != '',
                                    this.value == ''
                                )
                                .draw();
                        })
                        .on('keyup', function (e) {
                            e.stopPropagation();
 
                            $(this).trigger('change');
                            $(this)
                                .focus()[0]
                                .setSelectionRange(cursorPosition, cursorPosition);
                        });
                });
        },
    });
});
  </script>
  <script>
  $(function () {
    $("#datetimepicker1").datetimepicker({
      format: 'DD/MM/YYYY HH:mm',
    });
  });
</script>
  </body>
</html>

employee/templates/employee/feedback.html
{% extends 'Employee/base.html' %}
{% load crispy_forms_tags %}
{% load bootstrap4 %}
{% block content %}
{% for message in messages %}
    <div class="alert alert-success">
    <a class="close" href="#" data-dismiss="alert">×</a>
    {{ message }}
    </div>
{% endfor %}
<table class="table table-hover table-dark table-bordered">
  <colgroup>
    <col span="1" style="width: 13%;">
    <col span="1" style="width: 13%;">
    <col span="1" style="width: 3%;">
    <col span="1" style="width: 5%;">
    <col span="1" style="width: 10%;">
    <col span="1" style="width: 5%;">
    <col span="1" style="width: 43%;">
    <col span="1" style="width: 7%;">
 </colgroup>
 <thead>
   <tr>
     <th scope="col">Name</th>
     <th scope="col">Date of Birth</th>
     <th scope="col">Experience</th>
     <th scope="col">Notice Period</th>
     <th scope="col">Source</th>
     <th scope="col">Skill</th>
     <th scope="col">Assessment Score</th>
     <th scope="col">Resume</th>
   </tr>
 </thead>
 <tbody>
   <tr>
     <td>{{candidate.first_name}} {{candidate.last_name}}</td>
     <td>{{candidate.dateofbirth}}</td>
     <td>{{candidate.experience}}</td>
     <td>{{candidate.noticeperiod}}</td>
     <td>{{candidate.source}}</td>
     <td>{{candidate.skill}}</td>
     <td>{{candidate.assessment_data}}</td>
     <td>
         <a href="{{candidate.resume.url}}" class="btn btn-warning btn-sm">View</a>
     </td>
   </tr>
 </tbody>
</table>
{% if candidate_result.status_l1 == 'Selected' and candidate_result.status_l2 == 'Pending' and candidate_result.status_hr == 'Pending' %}
    <table class="table table-hover table-dark table-bordered">
 <thead>
   <tr>
     <th scope="col">L1 Feedback</th>
   </tr>
 </thead>
 <tbody>
   <tr>
     <td>{{candidate_result.feedback_l1}}</td>
   </tr>
 </tbody>
</table>
{% elif candidate_result.status_l1 == 'Selected' and candidate_result.status_l2 == 'Selected' and candidate_result.status_hr == 'Pending' %}
<table class="table table-hover table-dark table-bordered">
 <thead>
   <tr>
     <th scope="col">L1 Feedback</th>
     <th scope="col">L2 Feedback</th>
   </tr>
 </thead>
 <tbody>
   <tr>
     <td>{{candidate_result.feedback_l1}}</td>
     <td>{{candidate_result.feedback_l2}}</td>
   </tr>
 </tbody>
</table>
{% endif %}
<form method = 'POST' enctype="multipart/form-data"> {% csrf_token %}
{{form|crispy}}
<input type="submit" class="btn btn-primary" value="Update"></input>
</form>
{% endblock content %}

employee/templates/employee/index.html
{% extends 'employee/base.html' %}
{% load crispy_forms_tags %}
{% block content %}
    {% for message in messages %}
        <div class="alert alert-success">
        {{ message }}
        </div>
    {% endfor %}
    <h1>Interview Portal for Employee</h1>
    <p class="lead">This innovative online platform designed to streamline and optimize the interview process for both recruiters and candidates. It serves as a centralized hub where recruiters can manage and conduct interviews efficiently, while candidates can easily signup, attend, and follow up on their interviews.</p>
    <br>
{% endblock %}

employee/templates/employee/list.html
{% extends 'employee/base.html' %}
{% block content %}
<h2 class="text-center alert alert-info">Show Candidate Information</h2>
{% for message in messages %}
<div class="alert alert-success">
{{ message }}
</div>
{% endfor %}
{% if candidate_list %}
<table class="table table-hover table-dark table-bordered" id="userTable">
 <thead>
   <tr>
     <th scope="col">Name</th>
     <th scope="col">Phone Number</th>
     <th scope="col">Skill</th>
     <th scope="col">Experience</th>
     <th scope="col">Notice Period</th>
     <th scope="col">Source</th>
     <th scope="col">Date</th>
     <th scope="col">Actions</th>
   </tr>
 </thead>
 <tbody>
  {% for candidate in candidate_list %}
   <tr>
     <td>{{candidate.candidate_id.first_name}} {{candidate.candidate_id.last_name}}</td>
     <td>{{candidate.candidate_id.phone}}</td>
     <td>{{candidate.candidate_id.skill}}</td>
     <td>{{candidate.candidate_id.experience}}</td>
     <td>{{candidate.candidate_id.noticeperiod}}</td>
     <td>{{candidate.candidate_id.source}}</td>
     <td>{{candidate.candidate_id.created_at|date:'Y-m-d H:i'}}</td>
     <td>
         <a href="{% url 'employee:employee-feedback' candidate.candidate_id.id %}" class="btn btn-warning btn-sm">View</a>
     </td>
   </tr>
  {% endfor %}
 </tbody>
</table>
{% else %}
    <h2 class="text-center alert alert-warning">No Records</h2>
{% endif %}
<!--    Now the pagination section-->

{% if is_paginated %}
    <div class="pagination" >
        <span class="page-links" >
            {% if page_obj.has_previous %}
            <button class="btn btn-outline-primary" type="button"><a href="?page={{ page_obj.previous_page_number }}">Previous</a></button>
            {% endif %}
            <span class="page-current">
                Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
            </span>
            {% if page_obj.has_next %}
            <button class="btn btn-outline-primary" type="button"><a href="?page={{ page_obj.next_page_number }}">Next</a></button>
            {% endif %}
        </span>
    </div>
<br>
{% endif %}
{% endblock content %}

employee/templates/employee/login.html
{% extends 'employee/base.html' %}
{% load crispy_forms_tags %}
{% block content %}
<div class ='cover-container d-flex w-50 h-100 p-5 mx-auto flex-column'>
    <br>
    <h2 class="text-center alert alert-info">Employee Login</h2>
    {% for message in messages %}
        <div class="alert alert-success">
        {{ message }}
        </div>
    {% endfor %}
    <form method="post">
      {% csrf_token %}
      {{ form | crispy }}
        <br><button class="w-100 btn btn-lg btn-primary" type="submit">Login</button>
    </form>
</div>

{% endblock %}