candidate/urls.py
from django.urls import path
from .views import candidateProfileView,\
    candidateIndexView,\
    candidateSignupView,\
    candidateLoginView,\
    candidateLogoutView, \
    candidateUpdateView, \
    candidateAssessmentView

app_name = 'candidate'
urlpatterns = [
    path('',candidateIndexView,name='candidate-index'),
    path('assessment/',candidateAssessmentView,name='candidate-assessment'),
    path('profile/',candidateProfileView,name='candidate-profile'),
    path('signup/',candidateSignupView,name='candidate-signup'),
    path('login/',candidateLoginView,name='candidate-login'),
    path('logout/',candidateLogoutView,name='candidate-logout'),
    path('edit/<int:pk>',candidateUpdateView,name='candidate-edit'),
]

employee/urls.py
from django.urls import path
from . import views

app_name = 'employee'
urlpatterns = [
    path('',views.employeeIndexView,name='employee-index'),
    path('profile/',views.employeeProfileView,name='employee-profile'),
    path('status/<str:status>',views.employeeStatusList,name='employee-status'),
    path('list/?page=n',views.employeeListView,name='employee-list'),
    path('signup/',views.employeeSignupView,name='employee-signup'),
    path('feedback/<int:id>/',views.employeeFeedback,name='employee-feedback'),
    path('login/',views.employeeLoginView,name='employee-login'),
    path('logout/',views.employeeLogoutView,name='employee-logout'),
]

interview_portal/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings
from django.views.generic import TemplateView

urlpatterns = [
    path('',TemplateView.as_view(template_name='home.html'),name='index'),
    path('candidate/',include('candidate.urls',namespace='candidate')),
    path('employee/',include('employee.urls',namespace='employee')),
    path('admin/',include('empadmin.urls',namespace='admin')),
    path('jobs/',include('jobs.urls',namespace='jobs')),
    
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

jobs/urls.py
# urls.py
from django.urls import path
from . import views

app_name = 'jobs'

urlpatterns = [
    path('', views.job_list, name='job-list'),
    path('<int:pk>/', views.job_detail, name='job-detail'),
    path('create/', views.create_job, name='create-job'),
    path('<int:pk>/selectexam/<str:exam>', views.select_exam, name='select-exam'),
    path('<int:pk>/update/', views.update_job, name='update-job'),
    path('<int:pk>/delete/', views.delete_job, name='delete-job'),
]

templates/base.html
<!doctype html>
{% load static %}
<html lang="en" class="h-100">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <title>Interview Portal</title>
    <!-- Bootstrap core CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/js/bootstrap.bundle.min.js" integrity="sha384-JEW9xMcG8R+pH31jmWH6WWP0WintQrMb4s7ZOdauHnUtxwoG2vI5DkLtS3qm9Ekf" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="{% static 'css/styles.css' %}" />
  </head>
<body class="d-flex text-center text-white bg-dark">
  <div class="cover-container d-flex w-100 h-100 p-3 mx-auto flex-column min-vh-100">
  <header class="mb-auto">
    <div>
      <h3 class="float-md-start mb-0">Interview Portal</h3>
      <nav class="nav nav-masthead justify-content-center float-md-end">
        <a class="nav-link active" aria-current="page" href="{% url 'index' %}">Home</a>
        <a class="nav-link" href="{% url 'candidate:candidate-index' %}">Candidate</a>
        <a class="nav-link" href="{% url 'employee:employee-index' %}"> Employee</a>
      </nav>
    </div>
  </header>
   {% block content %}
    {% endblock %}
  <footer class="mt-auto text-white-50">
    <div>
      &copy;
      <span id="copyright">
          <script>document.getElementById('copyright').appendChild(document.createTextNode(new Date().getFullYear()))</script>
      </span>
      Interview Portal
  </div>
    <p><a>Designed by Vishesh Agarwal</a></p>
  </footer>
</div>
</body>
<script src="{% static 'js/script.js' %}"></script>
  <script>
  $(function () {
    $("#datetimepicker1").datetimepicker({
      format: 'DD/MM/YYYY HH:mm',
    });
  });
</script>
  </body>
</html>

templates/home.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block content %}
    {% for message in messages %}
        <div class="alert alert-success">
        <a class="close" href="#" data-dismiss="alert">×</a>
        {{ message }}
        </div>
    {% endfor %}
    <h1>Interview Portal for Candidate and Employee</h1>
    <p></p>
    <p class="lead">This innovative online platform designed to streamline and optimize the interview process for both recruiters and candidates. It serves as a centralized hub where recruiters can manage and conduct interviews efficiently, while candidates can easily signup, attend, and follow up on their interviews.</p>
    <br>
{% endblock %}