interview_portal/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings
from django.views.generic import TemplateView

urlpatterns = [
    path('',TemplateView.as_view(template_name='home.html'),name='index'),
    path('candidate/',include('candidate.urls',namespace='candidate')),
    path('employee/',include('employee.urls',namespace='employee')),
    path('admin/',include('empadmin.urls',namespace='admin')),
    path('jobs/',include('jobs.urls',namespace='jobs')),
    
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

jobs/urls.py
# urls.py
from django.urls import path
from . import views

app_name = 'jobs'

urlpatterns = [
    path('', views.job_list, name='job-list'),
    path('<int:pk>/', views.job_detail, name='job-detail'),
    path('create/', views.create_job, name='create-job'),
    path('<int:pk>/selectexam/<str:exam>', views.select_exam, name='select-exam'),
    path('<int:pk>/update/', views.update_job, name='update-job'),
    path('<int:pk>/delete/', views.delete_job, name='delete-job'),
]

jobs/models.py
from django.db import models
from candidate.models import Candidate

class Jobs(models.Model):
    title = models.CharField(max_length=255)
    company = models.CharField(max_length=255)
    location = models.CharField(max_length=100)
    description = models.TextField()
    requirements = models.TextField()
    posted_date = models.DateField()
    expiration_date = models.DateField()
    contact_information = models.TextField(blank=True, null=True)

    def __str__(self) -> str:
        return self.title()


class JobsExam(models.Model):
    exam_choice = (('Python', 'Python'), ('Java', 'Java'))
    job_id =  models.ForeignKey(Jobs,related_name='+',on_delete=models.CASCADE)
    exam = models.CharField(max_length=10, default='Python', choices=exam_choice, null=False, blank=False)

jobs/forms.py
from .models import Jobs
from django import forms

class DateInput(forms.DateInput):
    input_type = 'date'

class JobsForm(forms.ModelForm):
    class Meta:
        model = Jobs
        fields = '__all__'
        widgets = {
            'expiration_date': DateInput(),
            'posted_date': DateInput(),
        }

jobs/views.py
from django.shortcuts import render
from django.contrib.auth import logout
from django.http import HttpResponseRedirect
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.urls import reverse
from django.http import JsonResponse

from .models import Jobs,JobsExam
from .forms import JobsForm
# Create your views here.

@login_required(login_url="/admin/login/") 
def job_list(request):
    if not request.user.is_superuser:
        logout(request)
        messages.warning(request, 'Access Denied.')
        return HttpResponseRedirect(reverse('index'))
    
    jobs = Jobs.objects.all()
    return render(request, 'jobs/job_list.html', {'jobs': jobs})

@login_required(login_url="/admin/login/") 
def job_detail(request, pk):
    if not request.user.is_superuser:
        logout(request)
        messages.warning(request, 'Access Denied.')
        return HttpResponseRedirect(reverse('index'))
    
    job = Jobs.objects.get(pk=pk)
    exam = JobsExam.objects.filter(job_id=job)
    if exam.exists:
        exam = exam.first()
    else:
        exam = False
    return render(request, 'jobs/job_detail.html', {'job': job,'exam':exam})

@login_required(login_url="/admin/login/") 
def create_job(request):
    if not request.user.is_superuser:
        logout(request)
        messages.warning(request, 'Access Denied.')
        return HttpResponseRedirect(reverse('index'))
    
    if request.method == 'POST':
        form = JobsForm(request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('jobs:job-list'))
    else:
        form = JobsForm()
    return render(request, 'jobs/create_job.html', {'form': form})

@login_required(login_url="/admin/login/") 
def update_job(request, pk):
    if not request.user.is_superuser:
        logout(request)
        messages.warning(request, 'Access Denied.')
        return HttpResponseRedirect(reverse('index'))
    
    job = Jobs.objects.get(pk=pk)
    if request.method == 'POST':
        form = JobsForm(request.POST, instance=job)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('jobs:job-detail',args=[pk]))

    else:
        form = JobsForm(instance=job)
    return render(request, 'jobs/update_job.html', {'form': form})

@login_required(login_url="/admin/login/") 
def delete_job(request, pk):
    if not request.user.is_superuser:
        logout(request)
        messages.warning(request, 'Access Denied.')
        return HttpResponseRedirect(reverse('index'))
    
    job = Jobs.objects.get(pk=pk)
    if request.method == 'POST':
        job.delete()
        return HttpResponseRedirect(reverse('jobs:job-list'))
    return render(request, 'jobs/delete_job.html', {'job': job})

@login_required(login_url="/admin/login/") 
def select_exam(request, pk,exam):
    try:
        if not request.user.is_superuser:
            logout(request)
            messages.warning(request, 'Access Denied.')
            return HttpResponseRedirect(reverse('index'))
        
        job = Jobs.objects.get(pk=pk)
        if request.method == 'POST':
            JobsExam.objects.get_or_create(job_id=job,exam=exam)
            return JsonResponse({'status': 'Success'}, status=200)
    except Exception as e:
        return JsonResponse({'error': str(e)}, status=400)
    
    

jobs/templates/jobs/create_job.html
{% extends 'admin/base.html' %}
{% load crispy_forms_tags %}
{% block content %}
<div class ='cover-container d-flex w-50 h-100 p-5 mx-auto flex-column'>
    {% for message in messages %}
        <div class="alert alert-success">
        {{ message }}
        </div>
    {% endfor %}
    <br>
    <h2 class="text-center alert alert-info">Create Job Listing</h2>
    <form method="post">
      {% csrf_token %}
      {{ form | crispy }}
        <br><button class="w-100 btn btn-lg btn-primary" type="submit">Create</button>
    </form>
</div>
{% endblock %}

jobs/templates/jobs/delete_job.html
{% extends 'admin/base.html' %}
{% load crispy_forms_tags %}
{% load bootstrap4 %}
{% block content %}
<div class="container">
<h1>Delete Job Listing</h1>
    <p>Are you sure you want to delete "{{ job.title }}"?</p>
    <form method="post">
        {% csrf_token %}
        <button class="btn btn-lg btn-primary" data-bs-toggle="modal" data-bs-target="#exampleModal">Delete</button>
    </form></div>
{% endblock content%}

jobs/templates/jobs/job_detail.html
{% extends 'admin/base.html' %}
{% load crispy_forms_tags %}
{% load bootstrap4 %}
{% block style %}
<style>
  /* Darken the modal backdrop */
  .modal-backdrop {
      background-color: rgba(0, 0, 0, 0.5) !important;
  }
  /* Dark-themed modal content */
  .dark-modal .modal-content {
      background-color: #343a40;
      color: #fff;
  }
  .dark-modal .modal-header {
      border-bottom: 1px solid #454d55;
  }
  .dark-modal .modal-footer {
      border-top: 1px solid #454d55;
  }
  .dark-modal .modal-title {
      color: #fff;
  }
  .dark-modal .close {
      color: #fff;
      opacity: 0.5;
  }
  .dark-modal .close:hover {
      opacity: 0.75;
  }
  .dark-modal .btn-secondary {
      color: #fff;
      background-color: #6c757d;
      border-color: #6c757d;
  }
  .dark-modal .btn-secondary:hover {
      color: #fff;
      background-color: #5a6268;
      border-color: #545b62;
  }
</style>
{% endblock %}
{% block content %}
{% for message in messages %}
    <div class="alert alert-success">
    <a class="close" href="#" data-dismiss="alert">×</a>
    {{ message }}
    </div>
{% endfor %} 
<table class="table table-hover table-dark table-bordered">
  <colgroup>
    <col span="1" style="width: 13%;">
    <col span="1" style="width: 13%;">
    <col span="1" style="width: 13%;">
    <col span="1" style="width: 10%;">
    <col span="1" style="width: 10%;">
    <col span="1" style="width: 20%;">
    <col span="1" style="width: 10%;">
    <col span="1" style="width: 15%;">
 </colgroup>
 <thead>
    <tr>
        <th scope="col">Title</th>
        <th scope="col">Company</th>
        <th scope="col">Location</th>
        <th scope="col">Posted Date</th>
        <th scope="col">Expiration Date</th>
        <th scope="col">Contact Info</th>
        <th scope="col">Skill</th>
        <th scope="col">Actions</th>
      </tr>
 </thead>
 <tbody>
   <tr>
    <td>{{job.title}}</td>
    <td>{{job.company}}</td>
    <td>{{job.location}}</td>
    <td>{{job.posted_date}}</td>
    <td>{{job.expiration_date}}</td>
    <td>{{job.contact_information}}</td>
    {% if exam %}
      <td>{{exam.exam}}</td>
    {% else %}
    <td>
        <button type="button" class="btn btn-primary dropdown-toggle" data-toggle="modal" data-target="#darkModal">Skill</button>
        <!-- Dark-themed Modal -->
        <div class="modal fade dark-modal" tabindex="-1" role="dialog" id="darkModal">
            <div class="modal-dialog dark-modal" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title">Choose an Skill</h5>
                    </div>
                    <div class="modal-body">
                      <p>Select an option:</p>
                      <button type="button" class="btn btn-secondary" onclick="selectOption('Python')">Python</button>
                      <button type="button" class="btn btn-secondary" onclick="selectOption('Java')">Java</button>
                      </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                    </div>
                </div>
            </div>
        </div>
    </td>
    {% endif %}
    <td>
        <a href="{% url 'jobs:update-job' job.id %}" class="btn btn-warning btn-sm" title="Edit Job"><i class="fas fa-edit"></i></a>
        <a href="{% url 'jobs:delete-job' job.id %}" class="btn btn-warning btn-sm" title="Delete Job"><i class="fas fa-trash-alt"></i></a>
        </td>
   </tr>
 </tbody>
</table>
  <table class="table table-hover table-dark table-bordered">
    <thead>
      <tr>
        <th scope="col" width="25%" >Description</th> <td>{{job.description}}</td>
      </tr>
      <tr>
        <th scope="col" width="25%">Requirements</th><td>{{job.requirements}}</td>
      </tr>
    </thead>
    </table>
{% endblock content %}

{% block script %}
<!-- Include Bootstrap JS and jQuery -->
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.4/dist/umd/popper.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js"></script>

<script>
    // JavaScript function to handle option selection
    function selectOption(option) {
      var xhr = new XMLHttpRequest();
      if (option == 'Python'){
        xhr.open("POST", "{% url 'jobs:select-exam' job.id 'Python' %}", true);
      }
      else{
        xhr.open("POST", "{% url 'jobs:select-exam' job.id 'Java' %}", true);
      }
      xhr.setRequestHeader("Content-Type", "application/json");
      xhr.setRequestHeader("X-CSRFToken", getCookie("csrftoken"));
      xhr.onreadystatechange = function () {
          if (xhr.readyState == 4 && xhr.status == 200) {
              showSuccessNotification()
          }
          if (xhr.status == 400) {
              showNotSuccessNotification()
          }
        };
      xhr.send();
      }
    function showSuccessNotification() 
        {
            // Display update notification
            Swal.fire({
                title: 'Updating Data',
                text: 'Please wait...',
                icon: 'info',
                showConfirmButton: false,
                timer: 1000, // Display for 3 seconds (adjust as needed)
                allowOutsideClick: false
            }).then(() => {
                // After the update is complete, display confirmation message
                Swal.fire({
                    title: 'Update Successful!',
                    text: 'Data has been updated.',
                    icon: 'success',
                    timer: 1000,
                    showConfirmButton: false,
                }).then((result) => {
                // After the notification is closed, reload the page
                if (result.dismiss === Swal.DismissReason.timer) {
                    location.reload();
                }
            });
            });
        }
        function showNotSuccessNotification() 
        {
            // Display update notification
            Swal.fire({
              title: 'Error!',
              text: 'An unexpected error occurred.',
              icon: 'error',
              timer: 3000, // Display for 3 seconds (adjust as needed)
              allowOutsideClick: false
            }).then((result) => {
                // After the notification is closed, reload the page
                if (result.dismiss === Swal.DismissReason.timer) {
                    location.reload();
                }
            });
        }
    function getCookie(name) {
            var cookieValue = null;
            if (document.cookie && document.cookie !== '') {
                var cookies = document.cookie.split(';');
                for (var i = 0; i < cookies.length; i++) {
                    var cookie = cookies[i].trim();
                    if (cookie.substring(0, name.length + 1) === (name + '=')) {
                        cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                        break;
                    }
                }
            }
            return cookieValue;
        }
</script>
{% endblock %}

jobs/templates/jobs/job_list.html
{% extends 'admin/base.html' %}
{% block content %}
<h2 class="text-center alert alert-info">Job Listings</h2>
{% for message in messages %}
<div class="alert alert-success">
{{ message }}
</div>
{% endfor %}
{% if jobs %}
<table class="table table-hover table-dark table-bordered" id="userTable">
 <thead>
   <tr>
     <th scope="col">Title</th>
     <th scope="col">Company</th>
     <th scope="col">Location</th>
     <th scope="col">Posted Date</th>
     <th scope="col">Expiration Date</th>
     <th scope="col">Actions</th>
   </tr>
 </thead>
 <tbody>
  {% for job in jobs %}
   <tr>
     <td>{{job.title}}</td>
     <td>{{job.company}}</td>
     <td>{{job.location}}</td>
     <td>{{job.posted_date}}</td>
     <td>{{job.expiration_date}}</td>
     <td>
        <a href="{% url 'jobs:job-detail' job.id %}" class="btn btn-warning btn-sm" title="View Job"><i class="fas fa-eye"></i></a>
        <a href="{% url 'jobs:update-job' job.id %}" class="btn btn-warning btn-sm" title="Edit Job"><i class="fas fa-edit"></i></a>
        <a href="{% url 'jobs:delete-job' job.id %}" class="btn btn-warning btn-sm" title="Delete Job"><i class="fas fa-trash-alt"></i></a>
        </td>
    </tr>
  {% endfor %}
 </tbody>
</table>
{% else %}
    <h2 class="text-center alert alert-warning">No Records</h2>
{% endif %}
<!--    Now the pagination section-->

{% if is_paginated %}
    <div class="pagination" >
        <span class="page-links" >
            {% if page_obj.has_previous %}
            <button class="btn btn-outline-primary" type="button"><a href="?page={{ page_obj.previous_page_number }}">Previous</a></button>
            {% endif %}
            <span class="page-current">
                Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
            </span>
            {% if page_obj.has_next %}
            <button class="btn btn-outline-primary" type="button"><a href="?page={{ page_obj.next_page_number }}">Next</a></button>
            {% endif %}
        </span>
    </div>
<br>
{% endif %}
{% endblock content %}

jobs/templates/jobs/update_job.html
{% extends 'admin/base.html' %}
{% load crispy_forms_tags %}
{% block content %}
<div class ='cover-container d-flex w-50 h-100 p-5 mx-auto flex-column'>
    {% for message in messages %}
        <div class="alert alert-success">
        {{ message }}
        </div>
    {% endfor %}
    <br>
    <h2 class="text-center alert alert-info">Update Job Information</h2>
    <form method="post">
      {% csrf_token %}
      {{ form | crispy }}
        <br><button class="w-100 btn btn-lg btn-primary" type="submit">Update</button>
    </form>
</div>
{% endblock %}